### PR TITLE
*: fix assignments to make the new version of ineffassign happy

### PR DESCRIPTION
**Pull request by dseevr**
This fixes all the issues which the new version of ineffassign is complaining about.

### CODE REVIEW

**Comment by erikh** [comment]
oh, this is because ineffassign got bug fixes in IT that caused it to detect new ones. I ran into this the other night preparing the DB patch.

**Comment by dseevr** [comment]
Ahh, that explains... and because we have to invoke ineffassign once for each dir, it was just bailing on the first error.

Do you want me to tidy up all the spots it's complaining about and update the PR?

**Comment by erikh** [comment]
If you don't mind; yeah.

**Comment by dseevr** [comment]
Done and passing

**Comment by erikh** [comment]
hmm; I made several of these fixes already in the db patch but I guess I can rebase them out

**Comment by erikh** [comment]
LGTM. Simple enough that I'm just going to merge it.

**Pull request merged**
