### PR TITLE
volplugin,systemtests: cleanup socket on shutdown

### PR DESCRIPTION
**Pull request by erikh**
Signed-off-by: Erik Hollensbe <erik+github@hollensbe.org>

### CODE REVIEW

**Comment by unclejack** [comment]
@erikh This PR has some merge conflicts.

**Comment by erikh** [comment]
resolved, please don't merge until tests pass though, unless the failure is hte overlay bug

**Comment by erikh** [comment]
all fixed up; PTAL

**Comment by mapuri** [comment]
LGTM

**Comment by unclejack** [comment]
LGTM

**Pull request merged**
