### PR TITLE
systemtests: fix a missing err check caught by ineffassign

### PR DESCRIPTION
**Pull request by erikh**
Signed-off-by: Erik Hollensbe <github@hollensbe.org>

### CODE REVIEW

**Comment by erikh** [comment]
I've taken the liberty of adding the ineffassign check to our build pipeline. You can read more about it here: https://github.com/gordonklaus/ineffassign

**Comment by unclejack** [comment]
LGTM

**Comment by yuva29** [comment]
LGTM

**Comment by dseevr** [comment]
LGTM

**Pull request merged**
