### PR TITLE
config,volplugin,volcli,volmaster: s/tenant/Policy/g

### PR DESCRIPTION
**Pull request by erikh**
Don't waste a lot of time reviewing this, it's just a sed job. Maybe the comments or help messages would be the thing to focus on, everything should pass on tests.

### CODE REVIEW

**Comment by mapuri** [comment]
lgtm

Just curious, do we need a notion of tenant in volplugin eventually? May be it will be a policy-group or policy namespace of some sort.

**Comment by erikh** [comment]
Maybe, not sure that policies don't serve that now the way they're architected, though.

**Comment by mapuri** [comment]
sgtm. Also I think we should rename `config/tenant*.go` files to `config/policy*.go`?

**Comment by erikh** [comment]
yeah we should! I will fix.

**Pull request merged**
