### PR TITLE
*: split policy drivers for end-user

### PR DESCRIPTION
**Pull request by erikh**
Signed-off-by: Erik Hollensbe <erik+github@hollensbe.org>

### CODE REVIEW

**Comment by erikh** [comment]
@mapuri can you review this when you're available?

**Comment by mapuri** [comment]
@erikh 

changes LGTM, exposing the volplugin capabilities all the way to user gives them more control which is really flexible.

A few comments/questions on new behavior:
- this flexibility allows user to mix and match incompatible drivers. I am assuming we will let backend implementations fail appropriately. For instance, say CRUD is specified as ceph and Mount is nfs, it is not expected to work, right? It's not an issue as long as users know the compatible backends but I am more worried about catching and testing this in backends. The combinations are huge. May be we can fail early at the API invocation itself by validating that user only chooses compatible drivers?
- On similar lines, if user specifies a policy with just `Mount` driver mentioned as `ceph` then they won't be able to use this policy for snapshots without deleting and recreating it. Again not a big issue but something that user will need to be aware of. Should we instead tie drivers/backends with capabilities and initialize the `backendsDrivers` structure based on capabilities of the backend that user specifies? This won't allow mixing different backends though but I am wondering if we need that?

**Comment by erikh** [comment]
Yeah, I was thinking something similar when I started reading your reply :) Establish a compatibility matrix through driver acceptance (e.g., a map of driver -> supported pairs). This will be a pretty complex patch, though.

**Comment by erikh** [comment]
To be clear, that should be addressed in a separate patch, perhaps after the NFS feature is complete. Do you mind putting in an issue with your thoughts on the topic?

**Comment by mapuri** [comment]
> Establish a compatibility matrix through driver acceptance (e.g., a map of driver -> supported pairs

yeah, I think this keep rest of functionality simple and puts the complex compatibility check just at API handling level.

> Do you mind putting in an issue with your thoughts on the topic?

sgtm. Let me file an issue.

**Pull request merged**
