### PR TITLE
Debug info

### PR DESCRIPTION
**Pull request by unclejack**
This PR is based on #138 and that needs to be merged first.

This introduces a new info package. The new info package enables volplugin, volmaster and volsupervisor to print some debugging info when receiving SIGUSR1.

### CODE REVIEW

**Comment by erikh** [comment]
LGTM

**Comment by mapuri** [comment]
LGTM 

@unclejack @erikh shall we add etcd and docker version as well?

**Comment by erikh** [comment]
that's not a bad idea; @unclejack could you do that in a second patch?

**Comment by unclejack** [comment]
@erikh @mapuri: Sure, I can do that right away.

**Pull request merged**
