### PR TITLE
Fix unmap

### PR DESCRIPTION
**Pull request by erikh**
This creates a number of fixes for potential and infrequent failures in the mount/unmount process in volplugin. It also exposes a bug in docker via https://github.com/docker/docker/pull/21015 which is required to fix the issue for multiple atttempts at unmounting the same mountpoint on the same host.

### CODE REVIEW

**Comment by mapuri** [comment]
LGTM, I guess we need this as ceph won't allow mounting same volume more than once, right?

Just to understand the docker issue and the fix well, basically docker will continue to send unmount but has added an ID to mount and unmount request that volplugin can use to disregard unmount requests that don't have corresponding successful mount? Do we need to worry about these ID's being global v/s host local, looks like not becasue swarm will anyways create a volume on every host. Is that correct?

**Comment by erikh** [comment]
It's just not safe to do, ceph will let it happen though. There is a facility in ceph itself to make/remove these locks, but it hasn't proven very reliable to me yet.

**Comment by mapuri** [comment]
ah..ok, yeah I remember we had tried ceph locks before in volplugin.

**Comment by erikh** [comment]
```
Just to understand the docker issue and the fix well, basically docker will continue to send unmount but has added an ID to mount and unmount request that volplugin can use to disregard unmount requests that don't have corresponding successful mount? Do we need to worry about these ID's being global v/s host local, looks like not becasue swarm will anyways create a volume on every host. Is that correct?
```

To answer this, yes, that is the exact scenario we are hitting.

**Comment by erikh** [comment]
global vs. host local: these ids are generated locally and are per-mount, not per-volume, well at least once they arrive that is.

**Pull request merged**
