### PR TITLE
storage: rename ShowMapped to Mounted, gather mount points and other critical data from host.

### LINKED ISSUE #61: Retrieve mount points from /proc/self/mountinfo
This will enable better volplugin recovery on host restart.

### PR DESCRIPTION
**Pull request by erikh**
@unclejack @mapuri @jainvipin PTAL

closes #61

### CODE REVIEW

**Comment by mapuri** [comment]
LGTM

Just for my understanding, #61 refers to issue of restoring mounts on host restart but I don't see that instrumentation in this PR (unless I missed it), is it coming later? I am curious as I would like to see if it is always ok to just restore state from the host when the statestore might have changed while the host was down.

**Comment by erikh** [comment]
There should be a separate ticket for that. I may have closed it. I will 
create a new one.

This one just concedes that we need this support to continue. I have 
another patch I'm working on to implement the orchestration, I just 
wanted to get this in prematurely so it could be done more 
incrementally.

**Comment by erikh** [comment]
@mapuri I filed #76 to cover the full patch set required, PTAL and comment if you have any concerns about the design; I'd love your feedback.

**Comment by mapuri** [comment]
ok, thanks for clarifying @erikh , i will review #76 and post my comments there.

**Comment by erikh** [comment]
@unclejack PTAL when you are available. I have another patch in queue to file after this one is merged.

**Pull request merged**
