### PR TITLE
systemtests: wait for processes to be up

### PR DESCRIPTION
**Pull request by unclejack**

### CODE REVIEW

**Comment by mapuri** [comment]
@unclejack I think you can use one the existing utility functions in systemtest-utils package `ServiceStartAndWaitForUp()`

**Comment by unclejack** [comment]
@mapuri We're not using services for these and we can't use that.

**Comment by mapuri** [comment]
I see, I think we should be using services for testing but that is a different issue I guess :)

There is a more generic `WaitForDone()` in systemtest-utils as well that we could possibly use. I am hoping to not have to write new utility functions where systemtests utils already provides something. Feel free to add missing utilities there.

**Comment by erikh** [comment]
I agree, we should do this. @unclejack I can do this if you don't have time.

**Comment by erikh** [comment]
however, this seems to have fixed the issues in the system tests.

**Comment by unclejack** [comment]
@erikh @mapuri: I'll take a look and make the changes.

**Comment by erikh** [comment]
carrying this, I'll preserve your commits @unclejack

**Pull request closed without merging**
