### PR TITLE
api, config, db, storage, volplugin: Driver options as map[string]interface{}

### PR DESCRIPTION
**Pull request by yuva29**
This will let the DriverOptions to accept any data type. Helps new storage driver integrations.

Signed-off-by: Yuva Shankar <yuva.shankar29@gmail.com>

### CODE REVIEW

**Comment by dseevr** [comment]
@yuva29 can you trigger another build here?

**Comment by erikh** [comment]
@yuva29 did you rebase too?

**Comment by yuva29** [comment]
@dseevr Have to make changes. Will push again.

**Comment by yuva29** [comment]
Closing this. No longer required; issued new PR #460

**Pull request closed without merging**
