### PR TITLE
ansible: vendor recent fixes

### PR DESCRIPTION
**Pull request by dseevr**
I'm mostly interested in getting https://github.com/contiv/ansible/pull/263 merged, but there's a few other goodies, too.

cc @erikh, @mapuri

### CODE REVIEW

**Comment by mapuri** [comment]
LGTM

**Comment by erikh** [comment]
LGTM. Merge after CI passes, @dseevr

**Comment by dseevr** [comment]
Battery tests failed:  http://contiv.ngrok.io/job/Volplugin_CI/1064/consoleFull

Is this a re-trigger build or investigate?

**Comment by erikh** [comment]
as mentioned in slack, PTAL at this and make sure the create test is still working after your changes. a broken ceph could certainly lead to this.

**Comment by erikh** [comment]
You may also want to pull in latest master; it may have a fix you need.

**Comment by dseevr** [comment]
```

**Comment by dseevr** [comment]
Grabbed latest master changes, rebased, and now it's failing here:

```
TASK [contiv_network : set fwd mode] *******************************************
Friday 12 August 2016  17:04:50 -0700 (0:00:00.038)       0:06:54.017 ********* 
fatal: [mon0]: FAILED! => {"changed": true, "cmd": "netctl global set --fwd-mode \"bridge\"", "delta": "0:00:00.016325", "end": "2016-08-13 00:04:50.447554", "failed": true, "rc": 2, "start": "2016-08-13 00:04:50.431229", "stderr": "panic: runtime error: invalid memory address or nil pointer dereference\n[signal 0xb code=0x1 addr=0x38 pc=0x47eb60]\n\ngoroutine 1 [running]:\npanic(0x7e5100, 0xc82000e120)\n\t/usr/local/go/src/runtime/panic.go:481 +0x3e6\ngithub.com/contiv/netplugin/netctl.setGlobal(0xc820085680)\n\t/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl.go:637 +0x150\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x8668b8, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8aa0d0, 0x15, 0x0, ...)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:131 +0x1058\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc820085440, 0xc820085320, 0x0, 0x0)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:280 +0x1163\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.startApp(0x8654c8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8a9070, 0x12, 0x0, ...)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:209 +0x7c1\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x8654c8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8a9070, 0x12, 0x0, ...)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:59 +0x15f6\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).Run(0xc820085200, 0xc82000a050, 0x5, 0x5, 0x0, 0x0)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:173 +0xfb2\nmain.main()\n\t/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl/main.go:16 +0x12c", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by erikh** [comment]
OK, let's hold off on this patch right now; something may be elsewhere
screwing us up.

**Comment by dseevr** [comment]
I rebased off of our latest master and re-ran `make vendor-ansible` and now CI is passing.

This is the line that was failing in the original CI build:  https://github.com/contiv/netplugin/blob/d4fa8303339913fa9685dc6918b37c35caded37e/netctl/netctl.go#L634-L637

This is the last commit from the netplugin release which was active during the first CI build that failed.  Line 637 is failing because line 634 doesn't check for an error even though one is apparently happening.  The failing code here is new as of the netplugin release which broke the original CI run.

@gaurav-dalvi: any idea why that line could have failed?  The full log of that run is linked above.

@erikh is this okay to merge now?

**Comment by shaleman** [comment]
CC @abhinandanpb as well..

I'm guessing `global, _ := getClient(ctx).GlobalGet("global")` is returning an error which is not handled correctly..

**Comment by dseevr** [comment]
A subsequent CI run here passed, so I feel like that issue is probably happening intermittently.

I've updated our box_version to 0.7.0 and will run CI a few more times to make sure everything is kosher on our side.

**Comment by abhinandanpb** [comment]
@dseevr the issue was with netmaster not being ready when global state is configured. @mapuri added a patch for this.

**Comment by dseevr** [comment]
@abhinandanpb can you point me to the commit?

**Comment by abhinandanpb** [comment]
@dseevr ah looks like he yet to merge it . Its part of this https://github.com/contiv/ansible/pull/262/commits

**Comment by dseevr** [comment]
Great, I'll wait for that to be merged before I rebase/re-subtree and trigger CI here again.  Thanks @abhinandanpb and @shaleman

**Comment by erikh** [comment]
Don't rebase. Trust me. Just overwrite your branch.

**Comment by dseevr** [comment]
By "rebase", I mean blow away my commits on this branch, grab the latest from master (via rebasing), then run `make vendor-ansible` again

**Comment by erikh** [comment]
can we close this? We can start a new PR when this stuff is ready.

**Comment by dseevr** [comment]
Yep

**Pull request closed without merging**
