### PR TITLE
Makefile,build/scripts: adjust systemtests to have independent target…

### PR DESCRIPTION
**Pull request by erikh**
…s to be later used by jenkins

@mapuri

### CODE REVIEW

**Comment by dseevr** [comment]
LGTM

**Comment by mapuri** [comment]
LGTM

**Comment by mapuri** [comment]
@erikh , do you want to get rid of the `make ci` target as well? I don't think we would need it anymore with parallel builds

**Comment by erikh** [comment]
@mapuri I think I will do that in a separate patch so I don't have to run tests for this one again.

**Pull request merged**
