### PR TITLE
Upgrade box

### PR DESCRIPTION
**Pull request by erikh**
Upgrades ansible and vagrant box to 0.8.0

### CODE REVIEW

**Comment by erikh** [comment]
@mapuri sorry to bother but can you look into this test failure?

**Comment by mapuri** [comment]
@erikh 

looks like the vm didn't come up. I see that this is with the new vagrant box. Does it work for you locally? Let me try bringing it up as well.

```
==> mon0: Waiting for machine to boot. This may take a few minutes...
    mon0: SSH address: 127.0.0.1:2222
    mon0: SSH username: vagrant
    mon0: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by mapuri** [comment]
just verified the error happens for me locally as well which makes me think may be something is wrong with the box or the vbox/vagrant combination that we have on CI machines.

My local env is following, which is a bit old. Do we need to update CI machines?
```
ladmin@swvm168:~/goroot/src/github.com/contiv/volplugin$ VBoxManage --version
5.0.20r106931
ladmin@swvm168:~/goroot/src/github.com/contiv/volplugin$ vagrant --version
Vagrant 1.7.3
```

**Comment by erikh** [comment]
Yes, it works fine here.

I’m on 5.1 and probably installed the 5.1 guest additions into this 
box.

**Comment by erikh** [comment]
also vagrant will need to be brought up to 1.8.5 to support this change. been testing 0.6+ on 5.1 so I think the netplugin team should be fine until they're ready to upgrade.

**Comment by mapuri** [comment]
ok,sgtm

Will this new env ( vbox 5.1 and vagrant 1.8.5) work for netplugin? I vaguely remember some discussion on slack but not quite sure. If it works I will go ahead and update the CI machines.

ping @gaurav-dalvi @shaleman

**Comment by erikh** [comment]
It should, yes.

**Comment by gaurav-dalvi** [comment]
Yes it works. I have this on my mac and no issues so far.

**Comment by erikh** [comment]
merging the failed PR so get jenkins working again.

**Pull request merged**
