### PR TITLE
volci,volmaster: drop DELETE from DELETE URLs

### PR DESCRIPTION
**Pull request by unclejack**

### CODE REVIEW

**Comment by mapuri** [comment]
@unclejack LGTM

I think at some point we will need to make `/volumes/remove` and `/volumes/removeforce` consistent with this naming as well.

**Comment by erikh** [comment]
LGTM. Is this ready for merge?

**Comment by erikh** [comment]
(after CI runs)

**Comment by unclejack** [comment]
@erikh Yes, it should be good.

@mapuri: Sure, it's just that this was a smaller change to make.

**Pull request merged**
