### PR TITLE
Test improvements

### PR DESCRIPTION
**Pull request by erikh**
Several commits related to improving test reliability and flexibility

### CODE REVIEW

**Comment by erikh** [comment]
can I get a review of this? @mapuri @unclejack

**Comment by mapuri** [comment]
LGTM

just for my understanding, is `system-test-big` going to be the make target for stress and scale tests? Also you have not added to the `ci` target, is it because you see it run less often and in perhaps a separate jenkins job?

**Comment by erikh** [comment]
I just want it in there right now; we can evaluate whether or not it's 
best for the CI later.

**Comment by mapuri** [comment]
ok, sgtm

**Pull request merged**
