### PR TITLE
Bash autocomplete for volcli

### PR DESCRIPTION
**Pull request by vijayvikrant**
(1) Bash autocompletion file for volcli
(2) change to package this file in the tar

note: the ansible changes for copying the volcli file to /etc/bash_completion.d/ need to be done. They  will be done after the Makefile change is merged, as a tar with the changes is required to deploy.

for now, to test these changes one needs to,
sudo cp contrib/completion/bash/volcli /etc/bash_completion.d/
source /etc/bash_completion.d/volcli

```
[vagrant@mon0 volplugin]$ volcli
help    tenant  use     volume
[vagrant@mon0 volplugin]$ volcli tenant
delete  get     help    list    upload
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli tenant get tenant
tenant1  tenant2
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli tenant delete tenant
tenant1  tenant2
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli volume
create        force-remove  help          list          list-all      remove
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli volume create tenant
tenant1  tenant2
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli volume list tenant
tenant1  tenant2
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli volume remove tenant
tenant1/volume1  tenant2/volume2
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli volume force-remove tenant
tenant1/volume1  tenant2/volume2
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli use
force-remove  get           help          list
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli use get tenant
tenant1/volume1  tenant2/volume2
[vagrant@mon0 volplugin]$
[vagrant@mon0 volplugin]$ volcli use force-remove tenant
tenant1/volume1  tenant2/volume2
[vagrant@mon0 volplugin]$
```

### CODE REVIEW

**Comment by erikh** [comment]
This looks great! Everything looks great, but you should quote your variable expansions so that names with spaces do not cause trouble.

/cc @mapuri

**Comment by erikh** [comment]
my mistake, it looks like you did already.

LGTM

**Comment by mapuri** [comment]
this is really nice quality work and LGTM!

@vijayvikrant, @erikh 
I am new to code generation using go tools but looking at the bash script I am wondering if some some or all of this can be auto-generated (may be using `go generate` or `text/template` ?). So we can use the `GlobalFlags` and `Commands` variables in the `volcli/commands.go` file themselves to auto-generate values of `GLOBAL_COMMANDS` and `GLOBAL_OPTIONS`; we can also generate most of the `case` blocks of the bash script.

This will offer following immediate benefits:
- will reduce extra maintenance of the bash script  whenever we touch/rename sub-commands/flags without change of their meaning in volcli
- will give us a way to keep bash script logic closely tied to the go source code itself and hence improve trackability and testability

WDYT?

**Comment by erikh** [comment]
I think that's out of scope for this PR, but probably a good idea to do 
a larger, general pass of volcli idioms and rethink them. It was done 
pretty quickly.

Let's put an issue in (if you want to do this yourself, please assign) 
to tackle this at a later point.

-Erik

**Comment by mapuri** [comment]
cool, SGTM

I will create an issue to track this.

**Pull request merged**
