### PR TITLE
config,merge: new merge package created to house old config/merge.go.…

### PR DESCRIPTION
**Pull request by erikh**
… Tests rewritten to accomodate import cycle between the two, and simplified.

Signed-off-by: Erik Hollensbe <github@hollensbe.org>

### CODE REVIEW

**Comment by dseevr** [comment]
LGTM

**Comment by yuva29** [comment]
What is the need for this change?

**Comment by erikh** [comment]
@yuva29 it's an organizational one, just moving this out of the `config` package; it did not belong there.

**Comment by erikh** [comment]
other changes surround this move

**Pull request merged**
